name: update test refs

on:
  workflow_dispatch:

jobs:
  update_test_refs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tytanic (binary)
        uses: taiki-e/install-action@v2
        with:
          tool: tytanic@0.2.2

      - name: Update test refs
        run: tt update

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[update] test refs"